# Generated by Django 4.2.6 on 2023-10-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
